const fs = require('fs');
const L = [];
const out = (s) => L.push(s);

out('// Phase 2B \u2014 Supabase AnalysisStore.');
out('//');
out('// Extends SupabaseStore (which already implements every IngestionStore method)');
out('// and adds the analysis-specific read/write surface the analysis runner and');
out('// REST API need. Implemented against the live PostgreSQL backend via PostgREST.');
out('// Behavior mirrors MemoryAnalysisStore so intelligence is IDENTICAL in both');
out('// modes (Phase 2B spec \u00a713).');
out('');
out('import type { SupabaseClient } from \'@supabase/supabase-js\';');
out('import type {');
out('  AnalysisStore,');
out('  AnalysisRow,');
out('  DeveloperLink,');
out('  DeveloperRow,');
out('  LaunchWithToken,');
out('  MetaRow,');
out('  NewAnalysis,');
out('  SimilarityRow,');
out('  TokenMetaRow,');
out('} from \'./analysis-store.ts\';');
out('import type {');
out('  HolderSnapshot,');
out('  Launch,');
out('  MarketSnapshot,');
out('  Token,');
out('  TokenMetadata,');
out('  Transaction,');
out('  Wallet,');
out('} from \'../types/index.ts\';');
out('import { SupabaseStore, createSupabaseStore, type SupabaseStoreOptions } from \'./supabase-store.ts\';');
out('');
out('export interface SupabaseAnalysisStoreOptions extends SupabaseStoreOptions {}');
out('');
out('export function createSupabaseAnalysisStore(options?: SupabaseAnalysisStoreOptions): SupabaseAnalysisStore {');
out('  return new SupabaseAnalysisStore(createSupabaseStore(options).client);');
out('}');
out('');
out('export class SupabaseAnalysisStore extends SupabaseStore implements AnalysisStore {');
out('  constructor(client: SupabaseClient) {');
out('    super(client);');
out('  }');
out('');
out('  // ---- reads ---------------------------------------------------------------');
out('');
out('  async listTokens(limit?: number): Promise<Token[]> {');
out('    let query = this.client.from(\'tokens\').select(\'*\');');
out('    if (typeof limit === \'number\') query = query.limit(limit);');
out('    const { data, error } = await query;');
out('    if (error) throw this.dbError(\'list tokens\', error.message);');
out('    return (data ?? []) as unknown as Token[];');
out('  }');
out('');
out('  async listWallets(): Promise<Wallet[]> {');
out('    const { data, error } = await this.client.from(\'wallets\').select(\'*\');');
out('    if (error) throw this.dbError(\'list wallets\', error.message);');
out('    return (data ?? []) as unknown as Wallet[];');
out('  }');
out('');
out('  async getLaunchByToken(tokenId: string): Promise<Launch | null> {');
out('    const { data, error } = await this.client.from(\'launches\').select(\'*\').eq(\'token_id\', tokenId).maybeSingle();');
out('    if (error) throw this.dbError(\'get launch by token\', error.message);');
out('    return (data ?? null) as unknown as Launch | null;');
out('  }');
out('');
out('  async listMarketSnapshots(tokenId: string): Promise<MarketSnapshot[]> {');
out('    const { data, error } = await this.client.from(\'market_snapshots\').select(\'*\').eq(\'token_id\', tokenId);');
out('    if (error) throw this.dbError(\'list market snapshots\', error.message);');
out('    return (data ?? []) as unknown as MarketSnapshot[];');
out('  }');
out('');
out('  async listHolderSnapshots(tokenId: string): Promise<HolderSnapshot[]> {');
out('    const { data, error } = await this.client.from(\'holder_snapshots\').select(\'*\').eq(\'token_id\', tokenId);');
out('    if (error) throw this.dbError(\'list holder snapshots\', error.message);');
out('    return (data ?? []) as unknown as HolderSnapshot[];');
out('  }');
out('');
out('  async getTokenMetadataByToken(tokenId: string): Promise<TokenMetadata | null> {');
out('    const { data, error } = await this.client.from(\'token_metadata\').select(\'*\').eq(\'token_id\', tokenId).maybeSingle();');
out('    if (error) throw this.dbError(\'get token metadata\', error.message);');
out('    return (data ?? null) as unknown as TokenMetadata | null;');
out('  }');
out('');
out('  async listTransactionsByToken(tokenId: string): Promise<Transaction[]> {');
out('    const { data, error } = await this.client.from(\'transactions\').select(\'*\').eq(\'token_id\', tokenId);');
out('    if (error) throw this.dbError(\'list transactions by token\', error.message);');
out('    return (data ?? []) as unknown as Transaction[];');
out('  }');
out('');
out('  async listTransactionsByWallet(walletId: string): Promise<Transaction[]> {');
out('    const { data, error } = await this.client.from(\'transactions\').select(\'*\').eq(\'wallet_id\', walletId);');
out('    if (error) throw this.dbError(\'list transactions by wallet\', error.message);');
out('    return (data ?? []) as unknown as Transaction[];');
out('  }');
out('');

fs.writeFileSync('/Users/user/Downloads/MemeIntelligence/src/ingestion/analysis-store-supabase.ts', L.join('\n'));
console.log('part1:', L.length, 'lines');
