# Generates analysis-store-memory.ts using canonical Phase 2B types.
# Run: python3 scripts/gen_memory_store.py

T = '/Users/user/Downloads/MemeIntelligence/src/ingestion/analysis-store-memory.ts'

lines = []
a = lines.append

a('// Phase 2B \u2014 In-memory AnalysisStore (tests + offline demo).')
a('//')
a('// Extends MemoryStore (which already implements every IngestionStore method)')
a('// and adds the analysis-specific read/write surface the analysis runner and')
a('// REST API need. Mirrors the Supabase implementation\u2019s upsert semantics with')
a('// inspectable maps so intelligence behavior is IDENTICAL in both modes.')
a('//')
a('// Phase 2B spec \u00a713 \u2014 zero duplicated logic between modes.')
a('')
a("import type {")
a('  AnalysisStore,')
a('  AnalysisRow,')
a('  DeveloperLink,')
a('  DeveloperRow,')
a('  LaunchWithToken,')
a('  MetaRow,')
a('  NewAnalysis,')
a('  SimilarityRow,')
a('  TokenMetaRow,')
a("} from './analysis-store.ts';")
a("import type {")
a('  HolderSnapshot,')
a('  Launch,')
a('  MarketSnapshot,')
a('  Token,')
a('  TokenMetadata,')
a('  Transaction,')
a('  Wallet,')
a("} from '../types/index.ts';")
a("import { MemoryStore } from './memory-store.ts';")
a('')
a('export class MemoryAnalysisStore extends MemoryStore implements AnalysisStore {')
a('  readonly metas = new Map<string, MetaRow>();')
a('  private readonly tokenMetas = new Map<string, TokenMetaRow & { tokenId: string }>();')
a('  private readonly similarities = new Map<string, SimilarityRow & { sourceTokenId: string }>();')
a('  private readonly analyses = new Map<string, AnalysisRow>();')
a('  private readonly developers = new Map<string, DeveloperRow>();')
a('  private readonly developersById = new Map<string, DeveloperRow>();')
a('  private readonly developerWallets = new Map<string, { developer_id: string; wallet_id: string; relationship_type: string; confidence: number; evidence: string[] }>();')
a('  private seq = 0;')
a('')
a('  private nextId(prefix: string): string {')
a('    this.seq += 1;')
a('    return `${prefix}-${this.seq}`;')
a('  }')
a('')
a('  async listTokens(limit?: number): Promise<Token[]> {')
a('    const all = [...this.tokens.values()];')
a('    return typeof limit === \'number\' ? all.slice(0, limit) : all;')
a('  }')
a('')
a('  async listWallets(): Promise<Wallet[]> {')
a('    return [...this.wallets.values()];')
a('  }')
a('')
a('  async getLaunchByToken(tokenId: string): Promise<Launch | null> {')
a('    for (const launch of this.launches.values()) if (launch.token_id === tokenId) return launch;')
a('    return null;')
a('  }')
a('')
a('  async listMarketSnapshots(tokenId: string): Promise<MarketSnapshot[]> {')
a('    return [...this.marketSnapshots.values()].filter((s) => s.token_id === tokenId);')
a('  }')
a('')
a('  async listHolderSnapshots(tokenId: string): Promise<HolderSnapshot[]> {')
a('    return [...this.holderSnapshots.values()].filter((h) => h.token_id === tokenId);')
a('  }')
a('')
a('  async setTokenMetas(tokenId: string, rows: Array<{ slug: string; confidence: number }>): Promise<TokenMetaRow[]> {')
a('    for (const [key, val] of this.tokenMetas) if (val.tokenId === tokenId) this.tokenMetas.delete(key);')
a('    const result: TokenMetaRow[] = [];')
a('    for (const row of rows) {')
a('      const meta = this.metas.get(row.slug);')
a('      if (!meta) continue;')
a('      const entry: TokenMetaRow = { meta_id: meta.id, slug: row.slug, name: meta.name, confidence: row.confidence };')
a('      this.tokenMetas.set(`${tokenId}:${meta.id}`, { ...entry, tokenId });')
a('      result.push(entry);')
a('    }')
a('    return result;')
a('  }')
a('')
a('  async listTokenMetas(tokenId: string): Promise<TokenMetaRow[]> {')
a('    return [...this.tokenMetas.values()].filter((t) => t.tokenId === tokenId);')
a('  }')
a('')
a('  async setTokenSimilarities(tokenId: string, rows: SimilarityRow[]): Promise<void> {')
a('    for (const [key, val] of this.similarities) if (val.sourceTokenId === tokenId) this.similarities.delete(key);')
a('    for (const row of rows) this.similarities.set(`${tokenId}:${row.similar_token_id}`, { ...row, sourceTokenId: tokenId });')
a('  }')
a('')
a('  async insertAnalysis(analysis: NewAnalysis): Promise<AnalysisRow> {')
a('    const id = this.nextId(\'analysis\');')
a('    const row: AnalysisRow = {')
a('      id,')
a('      token_id: analysis.token_id,')
a('      analysis_type: analysis.analysis_type,')
a('      version: analysis.version,')
a('      score: analysis.score ?? null,')
a('      confidence: analysis.confidence,')
a('      result: analysis.result,')
a('      evidence: analysis.evidence,')
a('      created_at: new Date().toISOString(),')
a('    };')
a('    this.analyses.set(`${analysis.token_id}:${analysis.analysis_type}`, row);')
a('  async latestAnalyses(tokenId: string): Promise<AnalysisRow[]> {')
a('    const latest = new Map<string, AnalysisRow>();')
a('    for (const a of this.analyses.values()) {')
a('      if (a.token_id !== tokenId) continue;')
a('      const existing = latest.get(a.analysis_type);')
a('      if (!existing || a.created_at > existing.created_at) latest.set(a.analysis_type, a);')
a('    }')
a('    return [...latest.values()];')
a('  }')
a('')
a('  async ensureDeveloperByName(name: string): Promise<DeveloperRow> {')
a('    const existing = this.developers.get(name);')
a('    if (existing) return existing;')
a('    const row: DeveloperRow = { id: this.nextId(\'developer\'), name, primary_wallet_id: null };')
a('    this.developers.set(name, row);')
a('    this.developersById.set(row.id, row);')
a('    return row;')
a('  }')
a('')
a('  async getDeveloperByWallet(walletId: string): Promise<DeveloperLink | null> {')
a('    for (const link of this.developerWallets.values()) {')
a('      if (link.wallet_id !== walletId) continue;')
a('      const developer = this.developersById.get(link.developer_id);')
a('      if (developer) return { developer, relationship_type: link.relationship_type, confidence: link.confidence, evidence: link.evidence };')
a('    }')
a('    return null;')
a('  }')
a('')
a('  async getDeveloper(id: string): Promise<DeveloperRow | null> {')
a('    return this.developersById.get(id) ?? null;')
a('  }')
a('')
a('  async upsertDeveloperWallet(developerId: string, walletId: string, rel: string, confidence: number, evidence: string[]): Promise<void> {')
a('    this.developerWallets.set(`${developerId}:${walletId}`, { developer_id: developerId, wallet_id: walletId, relationship_type: rel, confidence, evidence });')
a('  }')
a('')
a('  async setLaunchDeveloper(launchId: string, developerId: string): Promise<void> {')
a('    for (const launch of this.launches.values()) if (launch.id === launchId) { launch.developer_id = developerId; return; }')
a('  }')
a('')
a('  async listLaunchesByDeveloper(developerId: string): Promise<LaunchWithToken[]> {')
a('    const result: LaunchWithToken[] = [];')
a('    for (const launch of this.launches.values()) {')
a('      if (launch.developer_id !== developerId) continue;')
a('      const token = [...this.tokens.values()].find((t) => t.id === launch.token_id) ?? null;')
a('      result.push({ ...launch, token });')
a('    }')
a('    return result;')
a('  }')
a('}')
a('')
a('export function createMemoryAnalysisStore(): MemoryAnalysisStore {')
a('  return new MemoryAnalysisStore();')
a('}')

with open(T, 'w') as f:
    f.write('\n'.join(lines) + '\n')
print('wrote', len(lines), 'lines to', T)

a('    return row;')
a('  }')
a('')
a('  async listAnalyses(tokenId: string): Promise<AnalysisRow[]> {')
a('    return [...this.analyses.values()].filter((a) => a.token_id === tokenId);')
a('  }')
a('')

a('  async getTokenMetadataByToken(tokenId: string): Promise<TokenMetadata | null> {')
a('    return this.metadata.get(tokenId) ?? null;')
a('  }')
a('')
a('  async listTransactionsByToken(tokenId: string): Promise<Transaction[]> {')
a('    return [...this.transactions.values()].filter((t) => t.token_id === tokenId);')
a('  }')
a('')
a('  async listTransactionsByWallet(walletId: string): Promise<Transaction[]> {')
a('    return [...this.transactions.values()].filter((t) => t.wallet_id === walletId);')
a('  }')
a('')
a('  async listMetas(): Promise<MetaRow[]> {')
a('    return [...this.metas.values()];')
a('  }')
a('')
a('  async upsertMeta(meta: { slug: string; name: string; parentSlug: string | null; description?: string | null }): Promise<MetaRow> {')
a('    const existing = this.metas.get(meta.slug);')
a('    if (existing) {')
a('      const updated: MetaRow = { ...existing, name: meta.name, parent_id: meta.parentSlug, description: meta.description ?? null };')
a('      this.metas.set(meta.slug, updated);')
a('      return updated;')
a('    }')
a('    const row: MetaRow = { id: this.nextId(\'meta\'), slug: meta.slug, name: meta.name, parent_id: meta.parentSlug, description: meta.description ?? null };')
a('    this.metas.set(meta.slug, row);')
a('    return row;')
a('  }')
a('')
